apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: jupyter-app
    name: jupyter-svc
    namespace: jupyter
    resourceVersion: "17061"
    uid: ec1eb467-21ab-4a07-b599-d7b455a6449e
  spec:
    clusterIP: 10.108.176.116
    clusterIPs:
    - 10.108.176.116
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - nodePort: 30000
      port: 8888
      protocol: TCP
      targetPort: 8888
    selector:
      app: jupyter-pods
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
